In [8]:
import numpy as np
##  Create array
### list
myPythonList = [1,9,8,3]
numpy_array_from_list = np.array(myPythonList)
### Directly in numpy
np.array([1,9,8,3])


array([1, 9, 8, 3])

In [10]:

### Shape
a = np.array([1,2,3])
print(a.shape)
### Type
print(a.dtype)
### 2D array
c = np.array([(1,2,3),
(4,5,6)])
print("2d Array",c)
### 3D array
d = np.array([[[1, 2,3],[4, 5, 6]],[[7, 8,9],[10, 11, 12]]])
print("3d Array",d)

(3,)
int32
2d Array [[1 2 3]
 [4 5 6]]
3d Array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
### Reshape
e = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)
print("After Reshape",e)
### Flatten
e.flatten()
print("After Flatten",e)
### hstack & vstack
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))
### random number
normal_array = np.random.normal(5, 0.5, 10)
print("Random Number",normal_array)
### asarray
A = np.matrix(np.ones((4,4)))
np.asarray(A)
print("Asrray", A)
### Arrange
print("Arrange",np.arange(1, 11))
### linspace
lin = np.linspace(1.0, 5.0, num=10)
print("Linspace", lin)
### logspace
log1 = np.logspace(3.0, 4.0, num=4)
print("Logspace", log1)
### Slicing
#### rows
e = np.array([(1,2,3), (4,5,6)])
print(e[0])
#### columns
print(e[:,1])
#### rows and columns
print(e[1, :2])

[[1 2 3]
 [4 5 6]]
After Reshape [[1 2 3]
 [4 5 6]]
After Flatten [[1 2 3]
 [4 5 6]]
Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
Random Number [5.46603423 6.09608871 5.40211228 4.86074807 5.70775981 4.32978783
 4.83320231 4.63792483 5.27159752 4.6732155 ]
Asrray [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arrange [ 1  2  3  4  5  6  7  8  9 10]
Linspace [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
Logspace [ 1000.          2154.43469003  4641.58883361 10000.        ]
[1 2 3]
[2 5]
[4 5]
