In [3]:
import tensorflow as tf

In [10]:
# rank 0
r0 = tf.constant(1, tf.int16)
print(r0)

# Decimal
r0_decimal = tf.constant(1.123, tf.float32)
print(r0_decimal)

# String
r0_string = tf.constant("Plain string object", tf.string)
print(r0_string)

tf.Tensor(1, shape=(), dtype=int16)
tf.Tensor(1.123, shape=(), dtype=float32)
tf.Tensor(b'Plain string object', shape=(), dtype=string)


In [11]:
# rank 1

r1_vector = tf.constant([1,3,5], tf.int16)
print(r1_vector)

r1_boolean = tf.constant([True, True, False], tf.bool)
print(r1_boolean)

tf.Tensor([1 3 5], shape=(3,), dtype=int16)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [12]:
# rank 2

r2_matrix = tf.constant([ [1, 2], [3, 4] ],tf.int16)

print(r2_matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [14]:
# rank 3

r3_matrix = tf.constant([ [[1, 2], [3, 4], [5, 6]] ], tf.int16)

print(r3_matrix)
print(r3_matrix.shape)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)
(1, 3, 2)


In [15]:
# type casting
type_float = tf.constant(3.123, tf.float32)
type_int = tf.cast(type_float, dtype=tf.int32)
print(type_float)
print(type_int)

tf.Tensor(3.123, shape=(), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


In [16]:
# Add
tensor_a = tf.constant([[1,2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)
tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


In [17]:
# Multiply
tensor_multiply = tf.multiply(tensor_a, tensor_b)
print(tensor_multiply)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [26]:
# Working with session in old way
tf.compat.v1.disable_eager_execution()

## Create, run and evaluate a session
x = tf.constant([2])
y = tf.constant([4])

## Create operator
multiply = tf.multiply(x, y)

## Create a session to run the code
with tf.compat.v1.Session() as sess:
    result_1 = sess.run(multiply)
    print(result_1)
sess.close()

[8]


In [27]:
# Working with session in old way
## Create, run and evaluate a session
x = tf.constant([2])
y = tf.constant([4])

## Create operator
multiply = tf.multiply(x, y)

print(result_1)


[8]
