In [3]:
import tensorflow as tf

In [10]:
# rank 0
r0 = tf.constant(1, tf.int16)
print(r0)

# Decimal
r0_decimal = tf.constant(1.123, tf.float32)
print(r0_decimal)

# String
r0_string = tf.constant("Plain string object", tf.string)
print(r0_string)

tf.Tensor(1, shape=(), dtype=int16)
tf.Tensor(1.123, shape=(), dtype=float32)
tf.Tensor(b'Plain string object', shape=(), dtype=string)


In [11]:
# rank 1

r1_vector = tf.constant([1,3,5], tf.int16)
print(r1_vector)

r1_boolean = tf.constant([True, True, False], tf.bool)
print(r1_boolean)

tf.Tensor([1 3 5], shape=(3,), dtype=int16)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [12]:
# rank 2

r2_matrix = tf.constant([ [1, 2], [3, 4] ],tf.int16)

print(r2_matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [13]:
# rank 3

r3_matrix = tf.constant([ [[1, 2], [3, 4], [5, 6]] ], tf.int16)

print(r3_matrix)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)
